// Builds dist/: per-brand theme (JS + d.ts + JSON), CSS variables, Tailwind/NativeWind preset, plus manifest.json.
// Output is deterministic (no timestamps) so CI can verify `dist/` is up to date.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {
  ROOT, MODES, listBrands, loadResolved, toNested, toCssValue, isPublic, readYAML, readJSON,
} from './lib.mjs';
import { loadSpecs } from './specs.mjs';

const DIST = path.join(ROOT, 'dist');
const HEADER = 'Generated by `npm run build`. Do not edit by hand.';
const sha = (s) => crypto.createHash('sha256').update(s).digest('hex').slice(0, 16);

const isIdent = (k) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k);
function serialize(v, ind = 0) {
  const pad = '  '.repeat(ind + 1), end = '  '.repeat(ind);
  if (v && typeof v === 'object') {
    const body = Object.entries(v).map(([k, x]) => `${pad}${isIdent(k) ? k : JSON.stringify(k)}: ${serialize(x, ind + 1)}`);
    return `{\n${body.join(',\n')}\n${end}}`;
  }
  return JSON.stringify(v);
}
function typeOf(v, ind = 0) {
  const pad = '  '.repeat(ind + 1), end = '  '.repeat(ind);
  if (v && typeof v === 'object') {
    const body = Object.entries(v).map(([k, x]) => `${pad}${isIdent(k) ? k : JSON.stringify(k)}: ${typeOf(x, ind + 1)};`);
    return `{\n${body.join('\n')}\n${end}}`;
  }
  return typeof v === 'number' ? 'number' : 'string';
}

const cssVar = (p) => `--bh-${p.replace(/\./g, '-')}`;

function buildCss(brand, light, dark) {
  const decl = (map, onlyDiff) => [...map]
    .filter(([p, t]) => isPublic(p, t) && toCssValue(t) !== null)
    .filter(([p, t]) => !onlyDiff || toCssValue(onlyDiff.get(p)) !== toCssValue(t))
    .map(([p, t]) => `  ${cssVar(p)}: ${toCssValue(t)};`).join('\n');
  return `/* ${HEADER}\n   Brand: ${brand}. Light is the default; dark applies with .dark (matches the app's global.css) or [data-theme="dark"]. */\n` +
    `:root,\n[data-theme="light"] {\n${decl(light)}\n}\n\n.dark,\n[data-theme="dark"] {\n${decl(dark, light)}\n}\n`;
}

function buildPreset(light) {
  const v = (p) => `var(${cssVar(p)})`;
  const group = (prefix, pick = () => true) => Object.fromEntries(
    [...light].filter(([p, t]) => isPublic(p, t) && p.startsWith(prefix + '.') && pick(p) && p.split('.').length === prefix.split('.').length + 1)
      .map(([p]) => [p.split('.').pop(), v(p)]));
  const lit = (prefix, fn = (t) => `${t.$value}`) => Object.fromEntries(
    [...light].filter(([p]) => p.startsWith(prefix + '.') && p.split('.').length === prefix.split('.').length + 1)
      .map(([p, t]) => [p.split('.').pop(), fn(t)]));
  const lh = lit('font.line-height');
  const fontSize = Object.fromEntries(Object.entries(lit('font.size')).map(([k, s]) => [k, [s, { lineHeight: lh[k] }]]));
  const preset = {
    theme: {
      extend: {
        colors: {
          ...group('color.bg'),
          content: group('color.text'),
          line: { DEFAULT: v('color.border.default'), strong: v('color.border.strong'), focus: v('color.border.focus') },
          accent: { DEFAULT: v('color.accent.default'), pressed: v('color.accent.pressed'), subtle: v('color.accent.subtle') },
          destructive: v('color.status.destructive'),
          success: v('color.status.success'),
          splash: { bg: v('color.brand.splash-bg'), fg: v('color.brand.splash-fg') },
        },
        spacing: lit('spacing'),
        borderRadius: lit('radius'),
        borderWidth: lit('border-width'),
        fontSize,
        fontWeight: lit('font.weight'),
        letterSpacing: lit('font.tracking'),
        fontFamily: {
          sans: [light.get('font.family.sans').$value],
          display: [light.get('font.family.display.web').$value],
          'display-ios': [light.get('font.family.display.ios').$value],
          'display-android': [light.get('font.family.display.android').$value],
        },
        opacity: lit('opacity', (t) => String(t.$value)),
        transitionDuration: lit('motion.duration'),
      },
    },
  };
  // Tailwind's own colour keys must stay usable; flatten bg group names are canvas/surface/... by construction.
  return `// ${HEADER}\n// Usage: presets: [require('@bakia/bithabit-design-system/tailwind-preset/<brand>')]\n// Colors use CSS variables so light/dark follow tokens.css (import it in global.css).\nmodule.exports = ${serialize(preset)};\n`;
}

fs.rmSync(DIST, { recursive: true, force: true });
const manifest = { designSystem: readJSON('package.json').version, brands: {}, components: {} };

for (const brand of listBrands()) {
  const out = path.join(DIST, brand);
  fs.mkdirSync(out, { recursive: true });
  const meta = readYAML(`brands/${brand}/brand.yaml`);
  const res = Object.fromEntries(MODES.map((m) => [m, loadResolved(brand, m)]));
  const nested = Object.fromEntries(MODES.map((m) => [m, toNested(res[m])]));

  fs.writeFileSync(path.join(out, 'theme.json'), JSON.stringify({ brand: { id: meta.id, name: meta.name }, ...nested }, null, 2) + '\n');
  fs.writeFileSync(path.join(out, 'theme.js'),
    `// ${HEADER}\nexport const brand = ${serialize({ id: meta.id, name: meta.name })};\n` +
    `export const light = ${serialize(nested.light)};\nexport const dark = ${serialize(nested.dark)};\n` +
    `export const themes = { light, dark };\n`);
  fs.writeFileSync(path.join(out, 'theme.d.ts'),
    `// ${HEADER}\nexport interface Theme ${typeOf(nested.light)}\n` +
    `export declare const brand: { id: string; name: string };\nexport declare const light: Theme;\nexport declare const dark: Theme;\n` +
    `export declare const themes: { light: Theme; dark: Theme };\n`);
  fs.writeFileSync(path.join(out, 'tokens.css'), buildCss(brand, res.light, res.dark));
  fs.writeFileSync(path.join(out, 'tailwind.preset.cjs'), buildPreset(res.light));

  manifest.brands[brand] = {
    name: meta.name,
    status: meta.status,
    tokensHash: sha(JSON.stringify(nested)),
    modes: MODES,
    surfaces: Object.keys(meta.surfaces).filter((s) => meta.surfaces[s]),
  };
}

for (const s of loadSpecs()) {
  manifest.components[s.spec.id] = {
    name: s.spec.name,
    version: s.spec.version,
    status: s.spec.status,
    category: s.spec.category,
    spec: `components/${s.dir}/${s.dir}.spec.yaml`,
    usage: `components/${s.dir}/${s.dir}.usage.md`,
    tokens: s.spec.tokens,
    contentHash: sha(s.raw + s.usage),
    sources: s.spec.sources ?? {},
    changelog: s.spec.changelog.slice(0, 3),
  };
}
fs.writeFileSync(path.join(DIST, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(`Built ${Object.keys(manifest.brands).length} brands, ${Object.keys(manifest.components).length} components -> dist/`);
