// Builds dist/: per-brand theme (JS + d.ts + JSON), CSS variables, Tailwind/NativeWind preset, plus manifest.json.
// Output is deterministic (no timestamps) so CI can verify `dist/` is up to date.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {
  ROOT, MODES, listBrands, loadResolved, toNested, toCssValue, isPublic, readYAML, readJSON,
} from './lib.mjs';

const COMPAT = readYAML('tokens/compat.yaml');
import { loadSpecs } from './specs.mjs';

const DIST = path.join(ROOT, 'dist');
const HEADER = 'Generated by `npm run build`. Do not edit by hand.';
const sha = (s) => crypto.createHash('sha256').update(s).digest('hex').slice(0, 16);

const isIdent = (k) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k);
function serialize(v, ind = 0) {
  const pad = '  '.repeat(ind + 1), end = '  '.repeat(ind);
  if (v && typeof v === 'object') {
    const body = Object.entries(v).map(([k, x]) => `${pad}${isIdent(k) ? k : JSON.stringify(k)}: ${serialize(x, ind + 1)}`);
    return `{\n${body.join(',\n')}\n${end}}`;
  }
  return JSON.stringify(v);
}
function typeOf(v, ind = 0) {
  const pad = '  '.repeat(ind + 1), end = '  '.repeat(ind);
  if (v && typeof v === 'object') {
    const body = Object.entries(v).map(([k, x]) => `${pad}${isIdent(k) ? k : JSON.stringify(k)}: ${typeOf(x, ind + 1)};`);
    return `{\n${body.join('\n')}\n${end}}`;
  }
  return typeof v === 'number' ? 'number' : 'string';
}

const cssVar = (p) => `--bh-${p.replace(/\./g, '-')}`;

function buildCss(brand, light, dark) {
  const decl = (map, onlyDiff) => [...map]
    .filter(([p, t]) => isPublic(p, t) && toCssValue(t) !== null)
    .filter(([p, t]) => !onlyDiff || toCssValue(onlyDiff.get(p)) !== toCssValue(t))
    .map(([p, t]) => `  ${cssVar(p)}: ${toCssValue(t)};`).join('\n');
  return `/* ${HEADER}\n   Brand: ${brand}. Light is the default; dark applies with .dark (matches the app's global.css) or [data-theme="dark"]. */\n` +
    `:root,\n[data-theme="light"] {\n${decl(light)}\n}\n\n.dark,\n[data-theme="dark"] {\n${decl(dark, light)}\n}\n`;
}

function buildCompatCss(brand, light, dark) {
  const block = (map) => Object.entries(COMPAT.colors)
    .map(([name, path]) => `    --color-${name}: ${map.get(path).$value};`).join('\n');
  return `/* ${HEADER}\n   Brand: ${brand}. Same --color-* variable names as Bakia/plan-de-vida global.css (NativeWind, darkMode: 'class').\n   Drop-in replacement for the color variables inside @layer base. */\n` +
    `@layer base {\n  :root {\n${block(light)}\n  }\n\n  .dark:root {\n${block(dark)}\n  }\n}\n`;
}

function buildPreset(light) {
  const cv = (name) => `var(--color-${name})`;
  const ev = (name) => `var(${cssVar(COMPAT.extras[name])})`;
  const lit = (prefix, fn = (t) => `${t.$value}`) => Object.fromEntries(
    [...light].filter(([p]) => p.startsWith(prefix + '.') && p.split('.').length === prefix.split('.').length + 1)
      .map(([p, t]) => [p.split('.').pop(), fn(t)]));
  const lh = lit('font.line-height');
  const fontSize = Object.fromEntries(Object.entries(lit('font.size')).map(([k, s]) => [k, [s, { lineHeight: lh[k] }]]));
  const preset = {
    theme: {
      extend: {
        colors: {
          splash: cv('splash'),
          foreground: cv('foreground'),
          accent: { DEFAULT: cv('accent'), pressed: ev('accent-pressed'), subtle: ev('accent-subtle') },
          background: cv('background'),
          surface: { DEFAULT: cv('surface'), alt: cv('surface-alt'), splash: cv('surface-splash') },
          muted: cv('muted'),
          destructive: cv('destructive'),
          today: cv('today'),
          border: cv('border'),
          card: cv('card'),
          input: { bg: cv('input-bg') },
          overlay: cv('overlay'),
          disabled: { DEFAULT: cv('disabled'), subtle: cv('disabled-subtle') },
          // Roles the app does not have yet (--bh-* variables):
          'accent-text': ev('accent-text'),
          'on-accent': ev('on-accent'),
          'destructive-text': ev('destructive-text'),
          positive: ev('positive'),
          focus: ev('focus'),
          'line-strong': ev('line-strong'),
          'on-today': ev('on-today'),
        },
        spacing: lit('spacing'),
        borderRadius: lit('radius'),
        borderWidth: { ...lit('border-width'), '1.5': light.get('border-width.medium').$value },
        fontSize,
        fontWeight: lit('font.weight'),
        letterSpacing: lit('font.tracking'),
        fontFamily: {
          sans: [light.get('font.family.sans').$value],
          serif: [light.get('font.family.display.ios').$value],
          'serif-android': [light.get('font.family.display.android').$value],
          'serif-web': [light.get('font.family.display.web').$value],
        },
        opacity: lit('opacity', (t) => String(t.$value)),
        transitionDuration: lit('motion.duration'),
      },
    },
  };
  // Tailwind's own colour keys must stay usable; flatten bg group names are canvas/surface/... by construction.
  return `// ${HEADER}\n// Usage: presets: [require('@bakia/bithabit-design-system/tailwind-preset/<brand>')]\n// Uses the BitHabit color names (foreground, background, surface, muted...). Colors read CSS variables:\n// --color-* from bithabit-compat.css and --bh-* from tokens.css (import both in global.css).\nmodule.exports = ${serialize(preset)};\n`;
}

fs.rmSync(DIST, { recursive: true, force: true });
const manifest = { designSystem: readJSON('package.json').version, brands: {}, components: {} };

for (const brand of listBrands()) {
  const out = path.join(DIST, brand);
  fs.mkdirSync(out, { recursive: true });
  const meta = readYAML(`brands/${brand}/brand.yaml`);
  const res = Object.fromEntries(MODES.map((m) => [m, loadResolved(brand, m)]));
  const nested = Object.fromEntries(MODES.map((m) => [m, toNested(res[m])]));

  fs.writeFileSync(path.join(out, 'theme.json'), JSON.stringify({ brand: { id: meta.id, name: meta.name }, ...nested }, null, 2) + '\n');
  fs.writeFileSync(path.join(out, 'theme.js'),
    `// ${HEADER}\nexport const brand = ${serialize({ id: meta.id, name: meta.name })};\n` +
    `export const light = ${serialize(nested.light)};\nexport const dark = ${serialize(nested.dark)};\n` +
    `export const themes = { light, dark };\n`);
  fs.writeFileSync(path.join(out, 'theme.d.ts'),
    `// ${HEADER}\nexport interface Theme ${typeOf(nested.light)}\n` +
    `export declare const brand: { id: string; name: string };\nexport declare const light: Theme;\nexport declare const dark: Theme;\n` +
    `export declare const themes: { light: Theme; dark: Theme };\n`);
  fs.writeFileSync(path.join(out, 'tokens.css'), buildCss(brand, res.light, res.dark));
  fs.writeFileSync(path.join(out, 'tailwind.preset.cjs'), buildPreset(res.light));
  fs.writeFileSync(path.join(out, 'bithabit-compat.css'), buildCompatCss(brand, res.light, res.dark));

  manifest.brands[brand] = {
    name: meta.name,
    status: meta.status,
    tokensHash: sha(JSON.stringify(nested)),
    modes: MODES,
    surfaces: Object.keys(meta.surfaces).filter((s) => meta.surfaces[s]),
    compatCss: `dist/${brand}/bithabit-compat.css`,
    theme: `dist/${brand}/theme.js`,
  };
}

for (const s of loadSpecs()) {
  manifest.components[s.spec.id] = {
    name: s.spec.name,
    version: s.spec.version,
    status: s.spec.status,
    category: s.spec.category,
    spec: `components/${s.dir}/${s.dir}.spec.yaml`,
    usage: `components/${s.dir}/${s.dir}.usage.md`,
    tokens: s.spec.tokens,
    contentHash: sha(s.raw + s.usage),
    props: s.spec.props.map((p) => ({ name: p.name, required: p.required })),
    variants: (s.spec.variants ?? []).map((v) => v.name),
    accessibilityRole: s.spec.accessibility.role,
    codeGaps: s.spec.code_gaps ?? [],
    // paths in the production app that the spec was verified against (text after the path is a note)
    codeSources: (s.spec.sources?.code ?? []).map((c) => ({ repo: c.repo, path: String(c.path).split(' ')[0], verified: c.verified, commit: c.commit })),
    sources: s.spec.sources ?? {},
    changelog: s.spec.changelog.slice(0, 3),
  };
}
fs.writeFileSync(path.join(DIST, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(`Built ${Object.keys(manifest.brands).length} brands, ${Object.keys(manifest.components).length} components -> dist/`);
