// Builds catalog/index.html: the whole visual catalog in ONE file (JS, CSS and fonts inlined).
// It opens by double-click (file://), works offline and needs no server. Output is deterministic so CI can check it is up to date.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { build } from 'vite';
import { ROOT } from './lib.mjs';

const SRC = path.join(ROOT, 'catalog-src');
const OUT = path.join(ROOT, 'catalog');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'bh-catalog-'));

await build({
  root: SRC,
  base: './',
  configFile: false,
  logLevel: 'warn',
  resolve: {
    // The reference components are written against React Native and shown on the web by react-native-web.
    alias: { 'react-native': 'react-native-web' },
    extensions: ['.web.tsx', '.web.ts', '.web.js', '.tsx', '.ts', '.js', '.mjs', '.json'],
  },
  define: { __DEV__: 'false', 'process.env.NODE_ENV': '"production"', global: 'globalThis' }, // react-native-web animations read global.performance
  server: { fs: { allow: [ROOT] } },
  build: {
    outDir: tmp,
    emptyOutDir: true,
    assetsInlineLimit: Number.MAX_SAFE_INTEGER, // fonts become data URIs
    cssCodeSplit: false,
    sourcemap: false,
    reportCompressedSize: false,
    chunkSizeWarningLimit: 100000,
    rollupOptions: {
      output: { codeSplitting: false },
      onwarn(warning, handler) {
        if (warning.code === 'MODULE_LEVEL_DIRECTIVE') return; // 'use client' in react-native-web is irrelevant here
        handler(warning);
      },
    },
  },
});

let html = fs.readFileSync(path.join(tmp, 'index.html'), 'utf8');
const read = (p) => fs.readFileSync(path.join(tmp, p.replace(/^\.?\//, '')), 'utf8');

// Inline the stylesheet(s) and the script(s). Replacement functions avoid '$' patterns being interpreted.
html = html.replace(/<link\b[^>]*rel="stylesheet"[^>]*href="([^"]+)"[^>]*>/g, (_, href) => `<style>${read(href)}</style>`);
html = html.replace(/<script\b[^>]*type="module"[^>]*src="([^"]+)"[^>]*><\/script>/g, (_, src) => {
  const js = read(src)
    .replace(/<\/script/gi, '<\\/script')        // would end the inline script early
    .replace(/<!--/g, '<\\!--')                   // legacy HTML comment opener inside script data
    .replace(/�/g, '\\ufffd');               // keep the file free of replacement characters (some libraries contain one as a literal)
  return `<script type="module">${js}</script>`;
});
// Vite puts the module script in <head>; modules are deferred, so #root exists when it runs.
html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by `npm run build-catalog`. Do not edit by hand. Open this file in a browser; no server needed. -->');

if (/(src|href)="(?!data:|#)[^"]*\.(js|css|woff2?)"/.test(html)) throw new Error('catalog build still references an external asset');
fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, 'index.html'), html);
fs.rmSync(tmp, { recursive: true, force: true });
console.log(`Built catalog/index.html (${(Buffer.byteLength(html) / 1024).toFixed(0)} KB)`);
